### ISSUE TITLE
Выброс исключения при передаче неверного пинкода

### ISSUE THREAD

**Issue by vbumazhenko** [diadoc/diadocsdk-1c-docs#819]
При отправке документа в Диадок с авторизацией через метод CreateConnectionByCertificate2(CertificateInfo), когда у объекта CertificateInfo методом setPin() установлен НЕправильный пинкод, появляется окно ввода пинкода.
У нас возникла необходимость вместо этого окна выбрасывать исключение, так как обработка выполняется на сервере и клиент не видит этого окна и создается впечатление, что программа зависает.
Прошу добавить соответствующий параметр, позволяющий вместо окна ввода пинкода выбрасывать исключение.

**Comment by GilimkhanovDenis** [comment]
Если политикой запуска приложение запрещён показ всплывающих окон, то исключение и так будет. Например, если выполняется регламентное задание на сервере.

`DiadocApiInvoiceApi.CreateConnectionByCertificate): ##300[Ошибка CryptoPro]Ошибка при расшифровке данных [2148073506:Provider could not perform the action since the context was acquired as silent.]`
